name = "TOONFormat"
uuid = "3eae6c5d-c92b-49d6-ab38-4ac5bd18d9c6"
version = "0.0.1"
authors = ["imohag9 <souidi.hamza90@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"

[compat]
Dates = "1.11.0"
JSON = "1.3.0"
OrderedCollections = "1.8.1"
StructUtils = "2.6.0"
julia = "1.11"
